export const ROLE_ERRORS = {
  NOT_FOUND: "ROLE_NOT_FOUND",

  SYSTEM_ROLE_DELETE: "SYSTEM_ROLE_DELETE",

  SYSTEM_ROLE_CODE_UPDATE: "SYSTEM_ROLE_CODE_UPDATE",

  SYSTEM_ROLE_CODE_RESERVED: "SYSTEM_ROLE_CODE_RESERVED",

  SUPER_ADMIN_ROLE_UPDATE: "SUPER_ADMIN_ROLE_UPDATE",

  SUPER_ADMIN_ROLE_DELETE: "SUPER_ADMIN_ROLE_DELETE",
} as const;
