export const USER_ERRORS = {
  NOT_FOUND: "USER_NOT_FOUND",

  EMAIL_EXISTS: "USER_EMAIL_EXISTS",

  ROLE_NOT_FOUND: "USER_ROLE_NOT_FOUND",

  CREATION_FAILED: "USER_CREATION_FAILED",

  SUPER_ADMIN_ASSIGNMENT: "SUPER_ADMIN_USER_ASSIGNMENT_FORBIDDEN",

  SUPER_ADMIN_STATUS_UPDATE: "SUPER_ADMIN_USER_STATUS_UPDATE",

  SUPER_ADMIN_ROLES_UPDATE: "SUPER_ADMIN_USER_ROLES_UPDATE",

  SUPER_ADMIN_DELETE: "SUPER_ADMIN_USER_DELETE",
} as const;
